version: "2"
plugins:
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "PSR1,PSR2"
      encoding: utf-8
  phpmd:
    enabled: true
    config:
      file_extensions:
        - php
      rulesets: "phpmd.xml"
  csslint:
    enabled: true
  eslint:
    enabled: true
  duplication:
    enabled: true
  fixme:
    enabled: true
exclude_patterns:
- src/font-awesome/
- vendor/