version: "2"
plugins:
  phpcodesniffer:
    enabled: false
  phpmd:
    enabled: true
    config:
      file_extensions:
        - php
      rulesets: "phpmd.xml"
  csslint:
    enabled: true
  eslint:
    enabled: true
  duplication:
    enabled: true
  fixme:
    enabled: true
exclude_patterns:
- src/font-awesome/
- .idea/
- tests/
- vendor/