---
kind: pipeline
type: docker
name: compliance

trigger:
  event:
    - push
    - pull_request
  branch:
    - develop
    - master

steps:
  - name: check-pr-branch-name
    image: alpine
    commands:
      - ./bin/check-branch-name.sh
    when:
      event:
        include:
          - pull_request
  - name: install
    image: composer
    commands:
      - composer install
  - name: check-php-compatibility
    image: php:8.0-cli-bullseye
    commands:
      - ./vendor/bin/phpcs

---
kind: pipeline
type: docker
name: tests

trigger:
  event:
    - push
    - pull_request
  branch:
    - develop
    - master

depends_on:
  - compliance

services:
  - name: database
    image: mariadb:10.8
    pull: always
    environment:
      MARIADB_ROOT_PASSWORD: wptestroot
      TZ: Europe/Berlin

steps:
  - name: install
    image: composer
    commands:
      - composer install
  - name: unit-tests
    image: php:8.0-cli-bullseye
    environment:
      CC_TEST_REPORTER_ID:
        from_secret: cc_test_reporter_id
    commands:
      - apt-get update && apt-get install -y git
      - pecl install xdebug
      - docker-php-ext-enable xdebug
      - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - chmod +x ./cc-test-reporter
      - ./cc-test-reporter before-build
      - XDEBUG_MODE=coverage ./vendor/bin/phpunit -c phpunit.xml
  - name: integration-tests-latest
    image: php:8.0-cli-bullseye
    commands:
      - apt-get update && apt-get install -y git subversion mariadb-client
      - pecl install xdebug
      - docker-php-ext-enable xdebug
      - docker-php-ext-install mysqli
      - ./bin/install-wp-tests.sh wptest_latest root wptestroot database
      - XDEBUG_MODE=coverage ./vendor/bin/phpunit -c phpunit-integration.xml
      - ./bin/report-code-coverage.sh
  - name: downgrade-phpunit
    image: composer
    commands:
      - composer require --dev --update-with-all-dependencies --ignore-platform-req=php "phpunit/phpunit:^7.5" "mockery/mockery:1.3.6" "sebastian/comparator:^3.0"
  - name: integration-tests-minimum
    image: php:7.4-cli-bullseye
    commands:
      - apt-get update && apt-get install -y subversion mariadb-client
      - docker-php-ext-install mysqli
      - ./bin/install-wp-tests.sh wptest_min root wptestroot database 5.6
      - ./vendor/bin/phpunit -c phpunit-integration.xml --no-coverage
  - name: codecov
    image: alpine
    environment:
      CODECOV_TOKEN:
        from_secret: codecov_token
    commands:
      - apk add curl gnupg coreutils git
      - curl https://uploader.codecov.io/verification.gpg | gpg --no-default-keyring --keyring trustedkeys.gpg --import
      - curl -Os https://uploader.codecov.io/latest/alpine/codecov
      - curl -Os https://uploader.codecov.io/latest/alpine/codecov.SHA256SUM
      - curl -Os https://uploader.codecov.io/latest/alpine/codecov.SHA256SUM.sig
      - gpgv codecov.SHA256SUM.sig codecov.SHA256SUM
      - sha256sum -c codecov.SHA256SUM
      - chmod +x codecov
      - ./codecov --file build/logs/clover.xml --flags unit
      - ./codecov --file build/logs/clover-integration.xml --flags integration

---
kind: pipeline
type: docker
name: release

steps:
  - name: check version tags
    image: alpine
    commands:
      - ./bin/check-version-tags.sh

depends_on:
  - tests

trigger:
  event:
    - tag
---
kind: signature
hmac: 500cfd9d5483a178c93012439f609b76ad1b13b375d166035fda411c69fb77d1

...
